# Generated by Django 3.1.5 on 2021-01-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_auto_20210115_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='category',
            field=models.CharField(default='cat', max_length=128),
            preserve_default=False,
        ),
    ]
