# Generated by Django 3.1.5 on 2021-01-19 14:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('appliances_type', models.CharField(default='none', max_length=120)),
                ('brand_name', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(default='none', upload_to='Appliance')),
                ('price', models.FloatField()),
                ('appliance_category', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('title_img', models.ImageField(default='hello', upload_to='blog_img')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Cabnets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabnet_color', models.CharField(max_length=128)),
                ('cabnet_img', models.ImageField(upload_to='cabnets')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('appliances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.appliances')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Applianes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Category_Appliances',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Combining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.cabnets')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('doors_guide', models.URLField(blank=True, null=True)),
                ('tall_unit_guide', models.URLField(blank=True, null=True)),
                ('x_tall_unit_guide', models.URLField(blank=True, null=True)),
                ('carcases_tech_guide', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='base_units')),
                ('sku', models.CharField(default='SKU', max_length=128)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_units', to='application.kitchencategory')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Worktop_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktop_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=30)),
                ('worktop_img', models.ImageField(upload_to='worktops/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktop_category', to='application.worktop_category')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.appliances')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.kitchen')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.units')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worktop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.worktop')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Units_intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('combine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.combining')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_qty', to='application.units')),
            ],
        ),
        migrations.AddField(
            model_name='units',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.unittype'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=15)),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('appliances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.appliances')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.kitchen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worktop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.worktop')),
            ],
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.kitchencategory'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='kitchen')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_image', to='application.kitchencategory')),
            ],
        ),
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_color', models.CharField(max_length=128)),
                ('door_img', models.ImageField(upload_to='doors')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_door', to='application.kitchen')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ManyToManyField(to='application.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='combining',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.doors'),
        ),
        migrations.AddField(
            model_name='combining',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_kitchen', to='application.kitchen'),
        ),
        migrations.AddField(
            model_name='combining',
            name='units',
            field=models.ManyToManyField(through='application.Units_intermediate', to='application.Units'),
        ),
        migrations.AddField(
            model_name='combining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='kitchen_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.combining'),
        ),
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.services'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='worktop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.worktop'),
        ),
        migrations.AddField(
            model_name='cabnets',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_cabnets', to='application.kitchen'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_category', to='application.category_applianes'),
        ),
    ]
