# Generated by Django 3.1.5 on 2021-01-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doors',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='images',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='combining',
            name='cabnet',
        ),
        migrations.RemoveField(
            model_name='combining',
            name='door',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='cabnet',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='door_color',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='kitchen'),
        ),
        migrations.DeleteModel(
            name='Cabnets',
        ),
        migrations.DeleteModel(
            name='Doors',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
