# Generated by Django 3.1.5 on 2021-01-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210110_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_image', to='application.kitchencategory'),
        ),
    ]
