# Generated by Django 3.1.5 on 2021-01-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210121_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('site_address', models.TextField()),
                ('phone', models.IntegerField()),
                ('room_ready', models.BooleanField(default=False)),
                ('remove_old_kitchen', models.BooleanField(default=False)),
                ('require_things', models.BooleanField(default=False)),
                ('your_budgets', models.CharField(max_length=100)),
            ],
        ),
    ]
