# Generated by Django 3.1.5 on 2021-09-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210905_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastatic',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
