# Generated by Django 3.1.5 on 2021-01-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210110_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabnets',
            name='img',
            field=models.ImageField(default='/p', upload_to='cabnets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doors',
            name='img',
            field=models.ImageField(default='/p', upload_to='doors'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cabnets',
            name='color',
        ),
        migrations.AddField(
            model_name='cabnets',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.color'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='doors',
            name='color',
        ),
        migrations.AddField(
            model_name='doors',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.color'),
            preserve_default=False,
        ),
    ]
