# Generated by Django 3.1.5 on 2021-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
