# Generated by Django 3.1.5 on 2021-09-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_metastatic_unique_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaInfo',
        ),
    ]
