# Generated by Django 3.1.5 on 2021-01-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210110_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabnets',
            name='color',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='doors',
            name='color',
            field=models.CharField(max_length=128),
        ),
    ]
