# Generated by Django 3.1.5 on 2021-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_contactus_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktop',
            name='for_sample',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='worktop',
            name='sample_price',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
    ]
