# Generated by Django 3.1.5 on 2021-01-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210126_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktop',
            name='for_sample',
        ),
        migrations.RemoveField(
            model_name='worktop',
            name='sample_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='sample_worktop',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
