# Generated by Django 3.1.5 on 2021-01-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210111_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabnets',
            old_name='img',
            new_name='cabnet_img',
        ),
        migrations.RenameField(
            model_name='doors',
            old_name='img',
            new_name='door_img',
        ),
    ]
