# Generated by Django 3.1.5 on 2021-01-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210111_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabnets',
            old_name='color',
            new_name='cabnet_color',
        ),
        migrations.RenameField(
            model_name='doors',
            old_name='color',
            new_name='door_color',
        ),
    ]
