# Generated by Django 3.1.5 on 2021-01-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210111_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_units', to='application.kitchencategory'),
        ),
    ]
