# Generated by Django 3.1.5 on 2021-01-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210128_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkedout',
            field=models.BooleanField(default=False),
        ),
    ]
