# Generated by Django 3.1.5 on 2021-01-11 21:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210111_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
