# Generated by Django 3.1.5 on 2021-02-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_cart_checkedout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='appliance_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='appliances_type',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='brand_name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category_applianes',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kitchencategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='units',
            name='sku',
            field=models.CharField(default='SKU', max_length=255),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='postcode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worktop',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worktop',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worktop',
            name='size',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worktop_category',
            name='worktop_type',
            field=models.CharField(max_length=255),
        ),
    ]
