# Generated by Django 3.1.5 on 2021-02-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20210201_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='units',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worktop',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
