# Generated by Django 3.1.5 on 2021-01-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
