# Generated by Django 3.1.5 on 2021-02-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210205_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='units',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worktop',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
