# Generated by Django 3.1.5 on 2021-01-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
