# Generated by Django 3.1.5 on 2021-02-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210207_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='worktop',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
