# Generated by Django 3.1.5 on 2021-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20210207_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('detail', models.TextField()),
                ('phone', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
    ]
