# Generated by Django 3.1.5 on 2021-01-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20210112_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='sku',
            field=models.CharField(default='SKU', max_length=128),
        ),
    ]
