# Generated by Django 3.1.5 on 2021-02-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_kitchen_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='door_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='street_address',
            field=models.TextField(blank=True, default='none', null=True),
        ),
    ]
