# Generated by Django 3.1.5 on 2021-01-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20210113_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='combining',
            name='cabnet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.cabnets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combining',
            name='door',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.doors'),
            preserve_default=False,
        ),
    ]
