# Generated by Django 3.1.5 on 2021-02-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20210209_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactactual',
            name='order_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactactual',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
