# Generated by Django 3.1.5 on 2021-02-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20210210_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=255)),
                ('home_name', models.CharField(max_length=255)),
                ('home_description', models.TextField()),
                ('kitchen_title', models.CharField(max_length=255)),
                ('kitchen_name', models.CharField(max_length=255)),
                ('kitchen_description', models.TextField()),
                ('worktop_title', models.CharField(max_length=255)),
                ('worktop_name', models.CharField(max_length=255)),
                ('worktop_description', models.TextField()),
                ('appliance_title', models.CharField(max_length=255)),
                ('appliance_name', models.CharField(max_length=255)),
                ('appliance_description', models.TextField()),
                ('design_title', models.CharField(max_length=255)),
                ('design_name', models.CharField(max_length=255)),
                ('design_description', models.TextField()),
                ('install_title', models.CharField(max_length=255)),
                ('install_name', models.CharField(max_length=255)),
                ('install_description', models.TextField()),
                ('contact_title', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_description', models.TextField()),
            ],
        ),
    ]
