# Generated by Django 3.1.5 on 2021-01-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20210113_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combining',
            name='cabnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.cabnets'),
        ),
        migrations.AlterField(
            model_name='combining',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.doors'),
        ),
    ]
