# Generated by Django 3.1.5 on 2021-03-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_cart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appliances',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='category_applianes',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Category_Appliances'},
        ),
        migrations.AlterModelOptions(
            name='contactactual',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='worktop',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='worktop_category',
            options={'ordering': ['-pk']},
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='accessories')),
                ('price', models.FloatField()),
                ('accessories_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.accessoriestype')),
            ],
        ),
    ]
