# Generated by Django 3.1.5 on 2021-01-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='appliance_category',
            field=models.CharField(default='app', max_length=128),
            preserve_default=False,
        ),
    ]
