# Generated by Django 3.1.5 on 2021-01-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_appliances_appliance_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
