# Generated by Django 3.1.5 on 2021-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20210309_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='sku',
            field=models.CharField(default='sku', max_length=128),
            preserve_default=False,
        ),
    ]
