# Generated by Django 3.1.5 on 2021-01-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20210117_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=15),
        ),
    ]
