# Generated by Django 3.1.5 on 2021-03-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_review_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.accessories'),
        ),
    ]
