# Generated by Django 3.1.5 on 2021-03-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_cart_accessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='metainfo',
            name='accessories_description',
            field=models.TextField(blank=True, default='Accessories', null=True),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='accessories_name',
            field=models.CharField(blank=True, default='Accessories', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='accessories_title',
            field=models.CharField(blank=True, default='Accessories', max_length=255, null=True),
        ),
    ]
