# Generated by Django 3.1.5 on 2021-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_worktop_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='img_alt_text',
            field=models.CharField(blank=True, default='alt', max_length=255, null=True),
        ),
    ]
