# Generated by Django 3.1.5 on 2021-03-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_kitchen_img_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriestype',
            name='slug',
            field=models.SlugField(blank=True, default='slug', null=True),
        ),
        migrations.AddField(
            model_name='category_applianes',
            name='slug',
            field=models.SlugField(blank=True, default='slug', null=True),
        ),
    ]
