# Generated by Django 3.1.5 on 2021-03-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20210323_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
