# Generated by Django 3.1.5 on 2021-04-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_demochat'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastatic',
            name='install_form_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metastatic',
            name='install_form_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metastatic',
            name='install_form_title',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metastatic',
            name='login_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metastatic',
            name='login_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metastatic',
            name='login_title',
            field=models.CharField(default='login', max_length=255),
        ),
        migrations.AddField(
            model_name='metastatic',
            name='signup_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metastatic',
            name='signup_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metastatic',
            name='signup_title',
            field=models.CharField(default='Signup', max_length=255),
        ),
    ]
