# Generated by Django 3.1.5 on 2021-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default='slug', max_length=255, null=True),
        ),
    ]
