# Generated by Django 3.1.5 on 2021-04-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_auto_20210406_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='combining',
            name='checkout',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
