# Generated by Django 3.1.5 on 2021-04-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_combining_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combining',
            name='checkout',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
